context:
  version: "0.0.4"

package:
  name: khiops-driver-azure
  version: ${{ version }}

source:
  url: https://github.com/KhiopsML/khiopsdriver-azure/archive/refs/tags/${{ version }}.tar.gz
  sha256: 4f05290a302a8a88064ede3cfb0e4728c4c8856c047ffde34d39217b1e9d8914

build:
  number: 0

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - ninja
  host:
    - spdlog ==1.15.3
    - azure-identity-cpp ==1.13.0
    - azure-storage-blobs-cpp ==12.14.0
    - azure-storage-files-shares-cpp ==12.14.0

tests:
  - script:
      - if: unix
        then: test -f $PREFIX/lib/libkhiopsdriver_file_azure${SHLIB_EXT}
        else:
          - if not exist %PREFIX%\Library\bin\libkhiopsdriver_file_azure.dll exit 1

about:
  homepage: https://khiops.org
  license: BSD-3-Clause-Clear
  license_file: LICENSE
  summary: Khiops driver to access files on Azure Cloud Storage
  description: The Azure driver plugin extends Khiops to enable processing of data files located on Azure Cloud Storage

extra:
  recipe-maintainers:
    - tristandeb1
    - sgouache
